services:
  - type: web
    name: flask-scraper
    env: python
    buildCommand: pip install -r requirements.txt && playwright install firefox
    startCommand: gunicorn app:app
    envVars:
      - key: URL
        sync: false
